#!/bin/env php
<?php

require 'Mail.php';
require 'vendor/autoload.php';

$pheanstalk = new Pheanstalk('localhost');
$mail = Mail::factory("mail");

while(true) {

	$job = $pheanstalk->watch('mailqueue')->ignore('default')->reserve();
	
	if($mail = unserialize($job->getData())) {
		
		echo $job->getId()."\n";
		$mail = unserialize($job->getData());		
		$mail->send($mail->to,$mail->headers,$mail->body);
		sleep(5);
	}
	else {
		
		echo 'Error in queue item'."\n";
	}

	$pheanstalk->delete($job);
}
